apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlan-middleware
  namespace: atlas
  labels:
    app: atlan-middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlan-middleware
  template:
    metadata:
      labels:
        app: atlan-middleware
    spec:
      imagePullSecrets:
        - name: github-docker-registry
      containers:
      - name: atlan-middleware
        image: ghcr.io/sumandas0/atlan-requests-test:main-3870e27
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::677185614191:role/enplajjp10-nodeinstance-role"  # Replace with your actual role ARN
        - name: S3_BUCKET_NAME
          value: "atlan-vcluster-enplajjp10-64005yjx6zw3"
        - name: S3_KEY_PREFIX
          value: "atlas/requests/"