apiVersion: v1
kind: Service
metadata:
  name: atlan-middleware-service
  namespace: atlan-middleware
  labels:
    app.kubernetes.io/name: atlan-requests-middleware
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: atlan-requests-middleware
    app.kubernetes.io/component: api