apiVersion: v1
kind: ServiceAccount
metadata:
  name: atlan-middleware-sa
  namespace: atlan-middleware
  labels:
    app.kubernetes.io/name: atlan-requests-middleware
    app.kubernetes.io/component: serviceaccount
  annotations:
    # Enable AWS IAM role for service accounts (IRSA) for EKS
    # Replace with your actual IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/YourS3AccessRole
automountServiceAccountToken: true